Added display filter validation
tomlegkov/marine-core pull request #21
Opened 2020-04-05 13:49 UTC by shaharyarn

2020-04-05 14:02 UTC, yehonatanz approved these changes

2020-04-05 15:35 UTC, tomlegkov commented on marine.c
> +WS_DLL_PUBLIC int validate_dfilter(char *dfilter) {
Rename to `validate_display_filter`, `dfilter` is an internal name.

2020-04-05 15:37 UTC, tomlegkov requested changes
Just rename the function :)

2020-04-06 10:25 UTC, tomlegkov approved these changes

2020-04-06 12:56 UTC, merged