Expose error codes
tomlegkov/marine-core pull request #34
Opened 2020-07-15 07:40 UTC by domerd

Goes along with [this](https://github.com/tomlegkov/marine-python/pull/38) PR.

2020-07-15 07:44 UTC, yehonatanz requested changes

2020-07-15 07:44 UTC, yehonatanz commented on marine.h
> +const int BadBPFErrorCode;
Shouldn't it be `extern`?

2020-07-15 07:44 UTC, yehonatanz commented on marine.h
> +const int BadBPFErrorCode;
Also, consts are written in `ALL_CAPS`

2020-07-15 18:46 UTC, yehonatanz requested changes

2020-07-15 18:46 UTC, yehonatanz commented on marine.c
> +WS_DLL_PUBLIC_DEF const int BadBPFErrorCode = -1;
Fix the casing here too (you changed only in `marine.h`)

2020-07-16 11:00 UTC, yehonatanz approved these changes

2020-07-16 17:56 UTC, tomlegkov requested changes

2020-07-16 17:56 UTC, tomlegkov commented on marine.c
> +WS_DLL_PUBLIC_DEF const int INVALID_FIELD_ERROR_CODE = -3;§
Weird symbol

2020-07-19 09:09 UTC, shaharyarn approved these changes

2020-08-13 09:12 UTC, shaharyarn commented
Closed in order to create a new PR.

2020-08-13 09:12 UTC, closed without merging