Added support of macros
tomlegkov/marine-core pull request #35
Opened 2020-07-16 13:16 UTC by shaharyarn

2020-07-16 14:08 UTC, yehonatanz requested changes
Had some cosmetic notes, but there's something more.
The `macro_indices` API is hard to understand, highly coupled to the implementation and does not make sense to an outside observer (API user). It took me a while to understand that the numbers represent "distance to the last field which is still part of the same macro".
Figure out a better way to tell the C code which fields are part of the same macro.
Some alternatives I thought about right now (can definitely be improved):
1. An array of booleans - `TRUE` if the field is the last in its group (or first, whatever) - will look like: `[0 0 1 0 1 1 1 0 0 0 0 1]`.
2. An array of ints that represent "group index" - will look like : `[0 0 0 0 1 2 2 3 4 5 5 5 5]`.

Either way, document your choice properly.

2020-07-16 14:08 UTC, yehonatanz commented on marine.c
> +    for (size_t i = 0; i < fields_len; i++) {
`memcpy`?

2020-07-16 14:08 UTC, yehonatanz commented on marine_benchmark.c
> +    memset(three_no_macro, 0, sizeof(three_no_macro));
Pretty sure `int three_no_macro[3] = {0};` will work

2020-07-16 14:08 UTC, yehonatanz commented on marine.c
> +    /* get ready for the next packet */
Document that this loop is separate since the previoud loop might skip on fields due to macros

2020-07-16 14:28 UTC, shaharyarn commented
Add an option to pass NULL to macro_indices to opt-out of the whole process (especially important if we are adding complexity by using different API).

2020-07-19 13:30 UTC, yehonatanz requested changes
Looks good, but:
1. Can you provide some benchmark (probably on the python client is better), so we can estimate the performance cost of the new  , improved macros mechanism?
2. Consider renaming `macro_indices` to `macro_ids` and `last_macro` to `last_in_macro`.
3. Document that macros must be contiguous

2020-07-19 14:21 UTC, shaharyarn commented
Before switching to c implementation:
![before](https://user-images.githubusercontent.com/62500302/87876980-32c94880-c9e4-11ea-8aec-f251c886dc68.png)

After switching:
![after](https://user-images.githubusercontent.com/62500302/87876991-3bba1a00-c9e4-11ea-8e3b-a4b2a5ca143f.png)

2020-07-19 15:05 UTC, yehonatanz approved these changes

2020-07-24 06:54 UTC, tomlegkov approved these changes

2020-07-24 06:54 UTC, tomlegkov commented on marine_benchmark.c
> +            {"Benchmark with BPF, Display filter and eight extracted fields", bpf,  dfilter, eight_fields, NULL, ARRAY_SIZE(eight_fields)},
Very nice!
Optionally, I think you could add a benchmark case with macros (similar to the one you added in Python).

2020-08-11 16:16 UTC, yehonatanz requested changes
Rebase your changes onto the current main branch to resolve your conflicts and fix your build.
Let's merge this :)

2020-08-17 17:38 UTC, yehonatanz approved these changes

2020-08-17 17:43 UTC, merged